- hosts: localhost
  vars_files:
    - vars.yml
  gather_facts: false
  tasks:
  - name: Deploy SIFT workstation 
    vmware_deploy_ovf:
        validate_certs: '{{ validate_certs }}'
        hostname: '{{ vcenter_address }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        allow_duplicates: false
        name: '{{ SIFT_name }}'
        networks: "{u'{{SIFT_vswitch}}':u'{{ SIFT_portgroup }}'}"
        datastore: '{{ SIFT_datastore }}'
        datacenter: '{{ SIFT_datacenter }}'
        resource_pool: '{{ SIFT_resource_pool}}'
        folder: '/{{ SIFT_datacenter }}/vm/{{ SIFT_folder }}'
        ovf: '{{SIFT_OVA_file}}'
        wait_for_ip_address: yes 
        power_on: yes
    delegate_to: localhost
    register: result
