---

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"
  become: true

- name: remove docker list since it causes errors
  file:
      path: /etc/apt/sources.list.d/docker.list
      state: absent

- name: remove docker list save since it causes errors
  file:
      path: /etc/apt/sources.list.d/docker.list.save
      state: absent

- name:  add the INetSim Debian Archive repository to apt sources
  apt_repository:
    repo: deb http://www.inetsim.org/debian/ binary/
    state: present
    update_cache: no
    filename: inetsim.list

- name: access the Debian package sources
  apt_repository:
    repo: deb-src http://www.inetsim.org/debian/ source/
    state: present
    update_cache: no
    filename: inetsim.list


- name: verify the digital signature on the INetSim Debian
  apt_key: 
    url: https://www.inetsim.org/inetsim-archive-signing-key.asc
    state: present 

- name: verify the digital signature for virtualbox1
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present 

- name: verify the digital signature for virtualbox2
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc  
    state: present 

- name: update virtualbox 
  shell: "echo 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib' >> /etc/apt/sources.list"

- name: Update all packages to the latest version
  apt:
    upgrade: full
    update_cache: yes
  become: true

  
- name: install python related pre-requirement packages
  package:
    name:
      - python
      - python-pip
      - python-dev
      - python-virtualenv
      - python-setuptools
    state: latest
  
    
- name: install misc pre-requirement packages
  package: 
    name:
      - libjpeg-dev
      - zlib1g-dev 
      - libcurl3
      - libpng12
      - libvpx3  
      - libsdl-ttf2
      - swig
      - mongodb
      - libffi-dev
      - libssl-dev
      - inetsim
      - virtualbox-6.1
    state: latest


- name: Download vagrant
  get_url: 
   url: "https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb"
   dest: /tmp/vagrant_2.2.7_x86_64.deb

- name: Install vagrant 
  apt: 
    deb: "/tmp/vagrant_2.2.7_x86_64.deb"


- name: Download VirtualBox extension pack
  get_url:
    url: "https://download.virtualbox.org/virtualbox/6.1.4/Oracle_VM_VirtualBox_Extension_Pack-6.1.4.vbox-extpack"
    dest: /tmp/
    force: yes


- name: Install VirtualBox extension pack
  shell: "echo 'y' | VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-6.1.4.vbox-extpack"



- name: clean up extension pack for virtualbox file 
  file:
    state: absent
    path: "/tmp/Oracle_VM_VirtualBox_Extension_Pack-6.1.4.vbox-extpack"
  become: true

- name: clean up vagrant and virtualbox files 
  file:
    state: absent
    path: "/tmp/vagrant_2.2.7_x86_64.deb"
  become: true
  